# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'
services:
  playerslist:
    image: playerslist
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    external_links:
      - postgres:postgres
    entrypoint:
      - bash 
      - ./run-dev.bash
    network_mode: bridge

